name: Build LaTeX PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # use your LaTeX container
    container:
      image: ghcr.io/kvn8888/latex-resume-builder:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install git
        run: |
          apt-get update
          apt-get install -y git

      - name: Compile all .tex files
        run: |
          # ensure we're in /github/workspace
          cd "$GITHUB_WORKSPACE"

          # make output dir
          mkdir -p pdf

          # compile each .tex at the root of the repo
          for tex in *.tex; do
            echo "Compiling $tex …"
            latexmk -pdf \
              -interaction=nonstopmode \
              -outdir=pdf \
              "$tex"
          done

          echo "Built PDFs:"
          ls -l pdf

      - name: Upload compiled PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: pdf/*.pdf

      - name: Commit & push PDFs back to main
        if: github.ref == 'refs/heads/main'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd "$GITHUB_WORKSPACE"

          # configure the commit author
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # stage and commit
          git add pdf
          git commit -m "Update compiled PDFs [skip ci]" \
            || echo "🎉 No changes to commit"

          # push via PAT
          git push "https://${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git" main