name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install TeX Live
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk

      - name: Compile all .tex files
        run: |
          find . -name '*.tex' | while read texfile; do
            filename=$(basename "$texfile" .tex)
            echo "Compiling $texfile ..."
            latexmk -pdf -interaction=nonstopmode -outdir=pdf "$texfile"
          done
      
      - name: Upload all PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: pdf/*.pdf
