name: Build LaTeX PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      #use docker image from docker hub
      image: k3vnc/personal:latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # this is the default

      - name: Compile all .tex files
        run: |
          find . -name '*.tex' | while read texfile; do
            filename=$(basename "$texfile" .tex)
            echo "Compiling $texfile ..."
            latexmk -pdf -interaction=nonstopmode -outdir=pdf "$texfile"
          done

      - name: Upload all PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: pdf/Chen_Kevin_SWEN_resume_*.pdf

      - name: Commit and push PDFs to repo
        if: github.ref == 'refs/heads/main'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch
          git checkout main
          git add pdf/*.pdf
          git commit -m "Update compiled PDFs [skip ci]" || echo "No changes to commit"
          git push "https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git" main